# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_sudoer_passwords:
  admin: $6$rounds=100000$JUkj1d3hCa6uFp6R$3rZ8jImyCpTP40e4I5APx7SbBvDCM8fB6GP/IGOrsk/GEUTUhl1i/Q2JNOpj9ashLpkgaCxqMqbFKdZdmAh26/

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  staging.eightloop.io:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://api.wordpress.org/secret-key/1.1/salt/
      # These CANNOT contain the characters "{%" or "{{" in succession
      auth_key: jB;;g^/yQN7QKZJ)7*yL|oklRP8_&3h~lIvQ@$XLS#R1lJ=m|L1_Y>Z>=Rdj,;SA
      secure_auth_key: ;AZ@I>-/>+/U:C5zx=Y-^stGQCy]8bc[?@&X,@Q7u2!>n$5w||ck&:DT{~#q?H2z
      logged_in_key: $,;yzZF8o{wQM>t+|:T5a@m.^_|tva*B{>s^IM/W+wp2e%Wc6D#(vJ2*>-r9d?1#
      nonce_key: 2OhFy`PWzG0{~Zq7GpEtFS{/ujttGJZ`p^Oh >-EmgAZ|2>+r}J`O,)(GNy:6V}f
      auth_salt: DopgQHJx+>btG@*LV%i]8u<NcAy+bml.0pi0z)Sq/%ou@r,8zBZj@y,2ape05T_*
      secure_auth_salt: P?j+-j?P92S$(<SN8~I- D}hhAb3HjLY^Jk#D~8+1*rz#8HpN:-05&7{B]=HsAIP
      logged_in_salt: du[;^f0tfd~hX|=_ LW|+&]]+!r|++#-kT1qyFEZ+/VWeEkKaq|;SN+?-cIQnLGF
      nonce_salt: u~-!`&h|v-qHCLr>=X*%3s>Kbcj(.,qcIyv-ztS8=h4#+$Z;6k`<]*vI|mLQH&`>
